/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.multiplica.prueba.cristiansrc.producto.repository.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProductDb service. Represents a row in the &quot;prueba_ProductDb&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.multiplica.prueba.cristiansrc.producto.repository.model.impl.ProductDbModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.multiplica.prueba.cristiansrc.producto.repository.model.impl.ProductDbImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductDb
 * @generated
 */
@ProviderType
public interface ProductDbModel extends BaseModel<ProductDb> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product db model instance should use the {@link ProductDb} interface instead.
	 */

	/**
	 * Returns the primary key of this product db.
	 *
	 * @return the primary key of this product db
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product db.
	 *
	 * @param primaryKey the primary key of this product db
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this product db.
	 *
	 * @return the uuid of this product db
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this product db.
	 *
	 * @param uuid the uuid of this product db
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this product db.
	 *
	 * @return the ID of this product db
	 */
	public long getId();

	/**
	 * Sets the ID of this product db.
	 *
	 * @param id the ID of this product db
	 */
	public void setId(long id);

	/**
	 * Returns the name of this product db.
	 *
	 * @return the name of this product db
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this product db.
	 *
	 * @param name the name of this product db
	 */
	public void setName(String name);

	/**
	 * Returns the description of this product db.
	 *
	 * @return the description of this product db
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this product db.
	 *
	 * @param description the description of this product db
	 */
	public void setDescription(String description);

}